name: Build and Deploy Spring Boot

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      JAVA_VERSION: "21"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: ${{ env.JAVA_VERSION }}

      - name: Build project with Maven
        run: mvn clean install -DskipTests=true

      - name: Run Tests
        run: mvn test

  # notify-develop:
  #   if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Send notification to Discord (develop)
  #       env:
  #         DISCORD_WEBHOOK_DEVELOP: ${{ secrets.DISCORD_WEBHOOK_DEVELOP }}
  #         BASE_URL: ${{ vars.DEV_BASE_URL }}
  #       run: |
  #         COMMIT_MESSAGE="$(git log -1 --pretty=%s)"
  #         COMMIT_URL="https://github.com/${{ github.repository }}/commit/${{ github.sha }}"
  #         curl -H "Content-Type: application/json" \
  #           -X POST \
  #           -d "{
  #             \"content\": \"🛠️ **Push a \`develop\`** en \`${{ github.repository }}\` por **${{ github.actor }}**.\n\n\
  #             🔗 **Swagger:** $BASE_URL/swagger-ui.html\n\
  #             🌐 **Home:** $BASE_URL\n\
  #             📝 **Commit:** ${COMMIT_MESSAGE}\n\
  #             🔍 [Ver commit](${COMMIT_URL})\"
  #           }" \
  #           $DISCORD_WEBHOOK_DEVELOP

  # - name: Deploy to Railway using API Token
  #   run: |
  #     curl -X POST https://backboard.railway.app/v2/deployments \
  #     -H "Authorization: Bearer ${{ secrets.RAILWAY_API_TOKEN }}" \
  #     -H "Content-Type: application/json" \
  #     -d '{"projectId": "${{ secrets.RAILWAY_PROJECT_ID }}"}'
